name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Installer les dépendances
      - name: Install dependencies
        run: npm install

      # 4. Générer Prisma
      - name: Generate Prisma client
        run: npx prisma generate

      # 5. Lancer les tests
      - name: Run tests
        run: npm test

      # 6. Build de l'app
      - name: Build project
        run: npm run build

      # 7. Déployer sur Render
      - name: Deploy to Render
        run: curl -X POST "$RENDER_DEPLOY_HOOK"
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
